export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          membership_tier: string;
          avatar_url: string | null;
          preferred_pillow: string;
          preferred_aromatherapy: string;
          preferred_newspaper: string;
          preferred_temperature: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          membership_tier?: string;
          avatar_url?: string | null;
          preferred_pillow?: string;
          preferred_aromatherapy?: string;
          preferred_newspaper?: string;
          preferred_temperature?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          membership_tier?: string;
          avatar_url?: string | null;
          preferred_pillow?: string;
          preferred_aromatherapy?: string;
          preferred_newspaper?: string;
          preferred_temperature?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      rooms: {
        Row: {
          id: string;
          slug: string;
          name: string;
          ref_code: string;
          pavilion: string;
          category: string;
          tag: string;
          tag_color: string | null;
          price_per_night: number;
          specs: Json;
          short_description: string;
          long_description: string;
          amenities: Json;
          key_amenities: Json;
          hero_image: string;
          gallery_images: Json;
          highlights: Json;
          rating: number;
          review_count: number;
          created_at: string;
        };
        Insert: {
          id: string;
          slug: string;
          name: string;
          ref_code: string;
          pavilion: string;
          category: string;
          tag: string;
          tag_color?: string | null;
          price_per_night: number;
          specs: Json;
          short_description: string;
          long_description: string;
          amenities: Json;
          key_amenities: Json;
          hero_image: string;
          gallery_images: Json;
          highlights: Json;
          rating?: number;
          review_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          ref_code?: string;
          pavilion?: string;
          category?: string;
          tag?: string;
          tag_color?: string | null;
          price_per_night?: number;
          specs?: Json;
          short_description?: string;
          long_description?: string;
          amenities?: Json;
          key_amenities?: Json;
          hero_image?: string;
          gallery_images?: Json;
          highlights?: Json;
          rating?: number;
          review_count?: number;
          created_at?: string;
        };
      };
      reservations: {
        Row: {
          id: string;
          ref_code: string;
          user_id: string | null;
          room_id: string | null;
          room_name: string;
          room_image: string;
          category: string;
          check_in: string;
          check_out: string;
          nights: number;
          adults: number;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          special_requests: string;
          privileges: Json;
          nightly_rate: number;
          subtotal: number;
          service_fee: number;
          taxes: number;
          total: number;
          status: 'confirmed' | 'active' | 'completed' | 'cancelled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ref_code: string;
          user_id?: string | null;
          room_id?: string | null;
          room_name: string;
          room_image: string;
          category: string;
          check_in: string;
          check_out: string;
          nights: number;
          adults: number;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          special_requests?: string;
          privileges?: Json;
          nightly_rate: number;
          subtotal: number;
          service_fee: number;
          taxes: number;
          total: number;
          status?: 'confirmed' | 'active' | 'completed' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ref_code?: string;
          user_id?: string | null;
          room_id?: string | null;
          room_name?: string;
          room_image?: string;
          category?: string;
          check_in?: string;
          check_out?: string;
          nights?: number;
          adults?: number;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          special_requests?: string;
          privileges?: Json;
          nightly_rate?: number;
          subtotal?: number;
          service_fee?: number;
          taxes?: number;
          total?: number;
          status?: 'confirmed' | 'active' | 'completed' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
      };
      dining_reservations: {
        Row: {
          id: string;
          ref_code: string;
          user_id: string | null;
          venue_id: string;
          venue_name: string;
          reservation_date: string;
          reservation_time: string;
          party_size: number;
          seating_area: string;
          guest_name: string;
          guest_email: string;
          guest_phone: string;
          dietary_notes: string;
          special_occasion: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          ref_code: string;
          user_id?: string | null;
          venue_id: string;
          venue_name: string;
          reservation_date: string;
          reservation_time: string;
          party_size: number;
          seating_area?: string;
          guest_name: string;
          guest_email: string;
          guest_phone?: string;
          dietary_notes?: string;
          special_occasion?: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          ref_code?: string;
          user_id?: string | null;
          venue_id?: string;
          venue_name?: string;
          reservation_date?: string;
          reservation_time?: string;
          party_size?: number;
          seating_area?: string;
          guest_name?: string;
          guest_email?: string;
          guest_phone?: string;
          dietary_notes?: string;
          special_occasion?: string;
          status?: string;
          created_at?: string;
        };
      };
      experience_bookings: {
        Row: {
          id: string;
          ref_code: string;
          user_id: string | null;
          experience_id: string;
          experience_title: string;
          booking_date: string;
          time_slot: string;
          guests_count: number;
          guest_name: string;
          guest_email: string;
          guest_phone: string;
          price_paid: string;
          special_requests: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          ref_code: string;
          user_id?: string | null;
          experience_id: string;
          experience_title: string;
          booking_date: string;
          time_slot: string;
          guests_count: number;
          guest_name: string;
          guest_email: string;
          guest_phone?: string;
          price_paid?: string;
          special_requests?: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          ref_code?: string;
          user_id?: string | null;
          experience_id?: string;
          experience_title?: string;
          booking_date?: string;
          time_slot?: string;
          guests_count?: number;
          guest_name?: string;
          guest_email?: string;
          guest_phone?: string;
          price_paid?: string;
          special_requests?: string;
          status?: string;
          created_at?: string;
        };
      };
      inquiries: {
        Row: {
          id: string;
          ref_code: string;
          user_id: string | null;
          topic: string;
          chamber_interest: string | null;
          guest_name: string;
          email: string;
          phone: string;
          arrival_date: string | null;
          special_requests: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          ref_code: string;
          user_id?: string | null;
          topic: string;
          chamber_interest?: string | null;
          guest_name: string;
          email: string;
          phone?: string;
          arrival_date?: string | null;
          special_requests?: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          ref_code?: string;
          user_id?: string | null;
          topic?: string;
          chamber_interest?: string | null;
          guest_name?: string;
          email?: string;
          phone?: string;
          arrival_date?: string | null;
          special_requests?: string;
          status?: string;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
